---
  - name : Update yum packages
    yum: name=* state=latest
    
  - name : install EPEL
    yum: name=epel-release state=latest
    
  - name : add deployment user
    action: user name=deploy password={{deploy_password}}

  - name: Change root password
    action: user name=root password={{root_password}}

  - name : add public SSH keys to deploy user
    authorized_key: user=deploy key=https://github.com/wadeschulz.keys

  - name: Remove sudo group rights
    action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

  - name: Add deploy user to sudoers
    action: lineinfile dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL) ALL" state=present

  - name: Disallow root SSH access
    action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present

  - name: Disallow password authentication for SSH
    action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present

  - name: Restart sshd
    action: service name=sshd state=restarted